services:
  web:
    build: .
    user: "node:node"
    volumes:
      - ./app:/home/app
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=development
    networks:
       - rede_homologacao_126
  
  networks:
    rede_homologacao_126:
      external: true
