services:
  web:
    build: .
    user: "node:node"
    container_name: consultorio-homolog
    volumes:
      - ./app:/home/app
    ports:
      - "3010:3010"
      - "3011:3011"
    environment:
      - NODE_ENV=development
    networks:
      - rede_homologacao_126
  
networks:
  rede_homologacao_126:
    external: true
